AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy FastAPI app on EC2 with Docker

Resources:

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user

          # Instalar git
          yum install git -y

          # Clonar repo (CAMBIA ESTO)
          git clone https://github.com/teban-coder/BTG-Pactual.git
          cd BTG-Pactual.git

          # Construir y correr Docker
          docker build -t btg-backend .
          docker run -d -p 8000:8000 btg-backend

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0